server:
  port: 8081
# 默认是用HikariCP作为数据源(连接池)
spring:
  datasource:
    username: root
#    password: 888
    password: 123456
#    url: jdbc:mysql://localhost:3306/boot_ecom
    url: jdbc:mysql://192.168.3.12:3306/boot_ecom
    driver-class-name: com.mysql.jdbc.Driver
    #    指定数据库的数据源为Druid(连接池)
    type: com.alibaba.druid.pool.DruidDataSource
#    initialization-mode: always
#    schema:
#      - classpath:sql/create_goods.sql
#      - classpath:sql/create_users.sql
#    data:
#      classpath:sql/create.sql

      #    Druid的参数配置
    #    shift+tab  向左移动

    initialSize: 5                            # 初始化时建立物理连接的个数
    minIdle: 5                                # 最小连接池数量
    maxActive: 20                             # 最大连接池数量
    maxWait: 60000                            # 获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000      # 1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据
    minEvictableIdleTimeMillis: 300000        # -
    validationQuery: SELECT 1 FROM DUAL       # 用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true                       # 申请连接的时候检测, 建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                       # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false                       # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: true              # 是否缓存preparedStatement，也就是PSCache. 在mysql下建议关闭

    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j                  # 属性类型是字符串，通过别名的方式配置扩展插件
    maxPoolPreparedStatementPerConnectionSize: 20   # PSCache的缓存大小
    useGlobalDataSourceStat: true                   #
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  application:
    name: ecom-goods      # 注册到eureka的名字

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  instance:
    prefer-ip-address: true   # 注册服务时显示ip地址
  client:
    register-with-eureka: true # 将自己注册到eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/
